export const project = [
  {
    id: 1,
    name: "The Pinnacle Residence",
    image: "/images/p1.jpg",

    description: "",
    images: [
      "/images/p1-1.jpg",
      "/images/p1-2.jpg",
      "/images/p1-3.jpg",
      "/images/p1-4.jpg",
      "/images/P1-5.jpg",
    ],
  },
  {
    id: 2,
    name: "The Pinnacle Residence",
    image: "/images/p2.jpg",
    description: "",
    images: [
      "/images/p2-1.jpg",
      "/images/p2-2.jpg",
      "/images/p2-3.jpg",
      "/images/p2-4.jpg",
    ],
  },
  {
    id: 3,
    name: "The Pinnacle Residence",
    image: "/images/p3.jpg",
    description: "",
    images: ["/images/p3-2.jpg", "/images/p3-3.jpg", "/images/p3-1.jpg"],
  },
  {
    id: 4,
    name: "The Pinnacle Residence",
    image: "/images/p4.jpg",
    description: "",
    images: [
      "/images/P4-1.jpg",
      "/images/P4-2.jpg",
      "/images/p4-3.jpg",
      "/images/p4-4.jpg",
      "/images/p4-5.jpg",
      "/images/p4-6.jpg",
      "/images/p4-7.jpg",
      "/images/p4-8.jpg",
      "/images/p4-9.jpg",
    ],
  },
  {
    id: 5,
    name: "The Pinnacle Residence",
    image: "/images/p5.jpg",
    description: "",
    images: [
      "/images/P5-6.jpg",
      "/images/P5-7.jpg",
      "/images/p5-1.jpg",
      "/images/p5-2.jpg",
      "/images/p5-3.jpg",
      "/images/p5-4.jpg",
      "/images/p5-5.jpg",
    ],
  },
  {
    id: 6,
    name: "The Pinnacle Residence",
    image: "/images/p6.jpg",
    description: "",
    images: ["/images/P6-1.jpg", "/images/P6-2.jpg", "/images/P6-3.jpg"],
    isNoMainImage: true,
  },
];
